part of 'timezone_to_country.dart';

const _map2 = {
  "America/Godthab": "GL",
  "America/Montreal": "CA",
  "America/Nipigon": "CA",
  "America/Pangnirtung": "CA",
  "America/Rainy_River": "CA",
  "America/Santa_Isabel": "MX",
  "America/Thunder_Bay": "CA",
  "America/Yellowknife": "CA",
  "Asia/Rangoon": "MM",
  "Australia/Currie": "AU",
  "Canada/Atlantic": "CA",
  "Canada/Central": "CA",
  "Canada/Eastern": "CA",
  "Canada/Mountain": "CA",
  "Canada/Newfoundland": "CA",
  "Canada/Pacific": "CA",
  "Europe/Kiev": "UA",
  "Europe/Uzhgorod": "UA",
  "Europe/Zaporozhye": "UA",
  "Pacific/Enderbury": "KI",
  "Pacific/Johnston": "US",
  "US/Alaska": "US",
  "US/Arizona": "US",
  "US/Central": "US",
  "US/Eastern": "US",
  "US/Hawaii": "US",
  "US/Mountain": "US",
  "US/Pacific": "US"
};
